# PyMOL script: EGFR domain III with pH-switch anchors
# Generated by analysis/05_anchor_geometry.py — do not hand-edit.
# Run with:  pymol explorer/anchor-view.pml
#
# Numbering note: this colours by PDB residue numbers, which in 6ARU are
# UniProt MINUS 24. Labels show the UniProt numbers we use everywhere else.

fetch 6ARU, async=0
hide everything
show cartoon, chain A
color grey80, chain A
bg_color white

# candidate epitope 415-466 (UniProt) = 391-442 (PDB)
select epitope, chain A and resi 391-442
color skyblue, epitope

# D416 (UniProt) = 392 (PDB) — partial  [in cluster]
select anchor_D416, chain A and resi 392
show sticks, anchor_D416
color orange, anchor_D416
label anchor_D416 and name CA, "D416"
show spheres, anchor_D416 and not name C+N+O
set sphere_scale, 0.3, anchor_D416

# H418 (UniProt) = 394 (PDB) — buried
select anchor_H418, chain A and resi 394
show sticks, anchor_H418
color firebrick, anchor_H418
label anchor_H418 and name CA, "H418"

# E421 (UniProt) = 397 (PDB) — partial  [in cluster]
select anchor_E421, chain A and resi 397
show sticks, anchor_E421
color orange, anchor_E421
label anchor_E421 and name CA, "E421"
show spheres, anchor_E421 and not name C+N+O
set sphere_scale, 0.3, anchor_E421

# E424 (UniProt) = 400 (PDB) — exposed  [in cluster]
select anchor_E424, chain A and resi 400
show sticks, anchor_E424
color forest, anchor_E424
label anchor_E424 and name CA, "E424"
show spheres, anchor_E424 and not name C+N+O
set sphere_scale, 0.3, anchor_E424

# H433 (UniProt) = 409 (PDB) — exposed
select anchor_H433, chain A and resi 409
show sticks, anchor_H433
color forest, anchor_H433
label anchor_H433 and name CA, "H433"

# E455 (UniProt) = 431 (PDB) — exposed  [in cluster]
select anchor_E455, chain A and resi 431
show sticks, anchor_E455
color forest, anchor_E455
label anchor_E455 and name CA, "E455"
show spheres, anchor_E455 and not name C+N+O
set sphere_scale, 0.3, anchor_E455

# D458 (UniProt) = 434 (PDB) — partial
select anchor_D458, chain A and resi 434
show sticks, anchor_D458
color orange, anchor_D458
label anchor_D458 and name CA, "D458"

# D460 (UniProt) = 436 (PDB) — partial
select anchor_D460, chain A and resi 436
show sticks, anchor_D460
color orange, anchor_D460
label anchor_D460 and name CA, "D460"

deselect
set label_size, 16
set label_color, black
set cartoon_transparency, 0.25, chain A
orient epitope

# green = exposed, orange = partial, red = buried
# spheres mark anchors in the reachable cluster
