/* h370-data.js — generated by analysis/08_h370_epitope.py. Do not hand-edit.
   Same values as data/derived/08-h370-neighbourhood.csv and
   data/derived/08-h370-clusters.csv. Rerun that script to change them.

   H370   every residue within 25 A of H370 that could carry a charge
          pair, nearest first. d is angstroms from H370's imidazole ring centre,
          rsa is relative solvent accessibility in 6ARU, cons is identical in
          mouse, cet is touched by cetuximab, pick is in the chosen cluster, and
          out says why a residue is not a candidate.
   CLUSTERS  anchor sets that fit one face, span in angstroms and angular spread in
          degrees. The H370 patch is this script's result; the 415-466 sets are
          step 05's clusters, with their spread computed here by the same face test,
          so both epitopes are judged on identical terms.
*/

const H370 = [
  {p:370,aa:"H",d:0.0,rsa:0.134,ex:"partial",cons:true,cet:false,pick:true},
  {p:368,aa:"D",d:5.5,rsa:0.122,ex:"partial",cons:true,cet:false,pick:true},
  {p:433,aa:"H",d:9.7,rsa:0.648,ex:"exposed",cons:true,cet:true,pick:false},
  {p:347,aa:"D",d:12.4,rsa:0.706,ex:"exposed",cons:true,cet:false,pick:false},
  {p:344,aa:"E",d:14.2,rsa:0.480,ex:"exposed",cons:true,cet:false,pick:true},
  {p:379,aa:"D",d:14.4,rsa:0.183,ex:"partial",cons:true,cet:false,pick:false},
  {p:358,aa:"H",d:16.6,rsa:0.500,ex:"exposed",cons:true,cet:false,pick:true},
  {p:460,aa:"D",d:16.9,rsa:0.186,ex:"partial",cons:true,cet:false,pick:false},
  {p:458,aa:"D",d:16.9,rsa:0.248,ex:"partial",cons:true,cet:false,pick:false},
  {p:400,aa:"E",d:17.3,rsa:0.147,ex:"partial",cons:true,cet:false,pick:true},
  {p:418,aa:"H",d:18.7,rsa:0.032,ex:"buried",cons:true,cet:false,pick:false,out:"buried in 6ARU"},
  {p:391,aa:"E",d:18.9,rsa:0.283,ex:"exposed",cons:true,cet:false,pick:true},
  {p:393,aa:"D",d:20.4,rsa:0.337,ex:"exposed",cons:false,cet:false,pick:false,out:"mouse has E"},
  {p:383,aa:"H",d:20.6,rsa:0.732,ex:"exposed",cons:false,cet:false,pick:false,out:"mouse has R"},
  {p:412,aa:"E",d:21.1,rsa:0.623,ex:"exposed",cons:false,cet:false,pick:false,out:"mouse has D"},
  {p:455,aa:"E",d:21.2,rsa:0.348,ex:"exposed",cons:true,cet:false,pick:false},
  {p:388,aa:"D",d:21.2,rsa:0.426,ex:"exposed",cons:true,cet:false,pick:false},
  {p:416,aa:"D",d:21.5,rsa:0.117,ex:"partial",cons:true,cet:false,pick:false},
  {p:421,aa:"E",d:21.9,rsa:0.210,ex:"partial",cons:true,cet:false,pick:true},
  {p:424,aa:"E",d:22.0,rsa:0.429,ex:"exposed",cons:true,cet:false,pick:true}
];

const CLUSTERS = [
  {n:"E344 H358 D368 H370 E391 E400 E421 E424",span:24.3,ang:58,src:"H370 patch"},
  {n:"D416 E421 E424 E455",span:22.6,ang:39,src:"415–466"},
  {n:"E424 E455 D458 D460",span:22.8,ang:24,src:"415–466"},
  {n:"H433 E455 D458 D460",span:23.6,ang:30,src:"415–466"},
  {n:"D416 E424 E455 D460",span:24.6,ang:38,src:"415–466"},
  {n:"D416 H418 E421 E424 E455",span:24.0,ang:44,src:"415–466, only if H418 is usable"}
];
